import { useEffect, useId, useRef, useState } from "react";
import { CardActions, Dialog, NotePreview, PeriodTabs, ToolCard } from "./WorkspaceUI";
import { supabase, usernameEmail } from "./supabase";
import Icon from "./Icon";
import {
  ACTION_SNIPPETS, BLANK_CALL, BLANK_CASE, CASE_FIELDS, CLAIM_STATUSES, EMAIL_TEMPLATES, FILTER_SKUS,
  ORDER_CODES, appendSnippet, buildClaimNote, buildFilterNote, buildNote, buildOrderNote,
  buildCallNote, detectCallDriver, followupState, formatClock, formatDuration, periodKey, readStorage, replacementCode, trendPoints
} from "./workdeskData";

const blankFilter = { reason: "Swapped Filter", search: "", selected: {}, notes: "" };
const blankOrder = { ...BLANK_CASE, category: "Warranty Replacement", reason: "WR-01" };
const blankClaim = { "Claim Number": "", "Tracking Number": "", "Claim Status": "Claim Issued", invoice: false };

function CallTimer({ running, seconds, onStart, onStop, onNew }) {
  return <section className={`timer-bar ${running ? "timer-running" : ""}`} aria-label="Call Timer">
    <div className="timer-label"><span className="timer-icon"><Icon name="phone" size={22}/></span><div><strong>Call Timer</strong><span className="timer-state" role="status"><i className={`status-dot ${running ? "running" : ""}`}/>{running ? "Call in progress" : "Ready for call"}</span></div></div>
    <strong className="timer-count" aria-label={`Elapsed time ${formatClock(seconds)}`}>{formatClock(seconds)}</strong>
    <p className="timer-hint">Stop &amp; Save creates a call report.</p>
    <div className="timer-actions"><button className={running ? "secondary-button" : "primary-button"} disabled={running} onClick={onStart}><Icon name="play"/>Start</button><button className={running ? "primary-button" : "secondary-button"} disabled={!running} onClick={onStop}><Icon name="stop"/>Stop &amp; Save</button><button className="ghost-button" onClick={onNew}><Icon name="plus"/>New Call</button></div>
  </section>;
}

function CallNotes({ call, setCall, followup, setFollowup, text, copy, reset, fold, toggle }) {
  const update = (field, value) => setCall({ ...call, [field]: value });
  return <ToolCard id="tool-call" title="Call Notes" icon="note" open={fold} onToggle={toggle} className="call-notes-card">
    <div className="call-notes-grid"><div className="call-form">
      <fieldset className="form-group"><legend>Customer details</legend><div className="field-layout customer-fields">
        {["Spoke With", "Name on the Account", "Order Num", "Email Address", "Contact #"].map((field) => <label key={field}>{field}<input value={call[field]} onChange={(event) => update(field, event.target.value)}/></label>)}
      </div></fieldset>
      <fieldset className="form-group"><legend>Conversation</legend><div className="stack-fields unpadded">
        <label>Reason for Calling<textarea rows="3" value={call["Reason for Calling"]} onChange={(event) => update("Reason for Calling", event.target.value)} placeholder="What does the customer need help with?"/></label>
        <label>ACTION TAKEN<textarea rows="4" value={call["ACTION TAKEN"]} onChange={(event) => update("ACTION TAKEN", event.target.value)} placeholder="Record the actions you completed…"/></label>
        <div className="snippet-row" role="group" aria-label="Quick insert into action taken"><span>Quick insert</span><div>{ACTION_SNIPPETS.map((snippet) => <button key={snippet} onClick={() => update("ACTION TAKEN", appendSnippet(call["ACTION TAKEN"], snippet))}>{snippet}</button>)}</div></div>
      </div></fieldset>
      <fieldset className="form-group"><legend>Call details &amp; follow-up</legend><div className="field-layout">
        <label>Offered FC/Cross Sell<select value={call["Offered FC/Cross Sell"]} onChange={(event) => update("Offered FC/Cross Sell", event.target.value)}><option value="">Select Y or N…</option><option value="Y">Y</option><option value="N">N</option></select></label>
        <label>AC Call ID<input value={call["AC Call ID"]} onChange={(event) => update("AC Call ID", event.target.value)}/></label>
        <div className={`followup-box span-all ${followup.needed ? "is-needed" : ""}`}><label className="check-label"><input type="checkbox" checked={followup.needed} onChange={(event) => setFollowup({ ...followup, needed: event.target.checked })}/><span>Follow-up needed</span></label>{followup.needed && <div className="followup-fields"><label>Follow-up Date<input type="date" value={followup.date} onChange={(event) => setFollowup({ ...followup, date: event.target.value })}/></label><label>Follow-up Note<input value={followup.note} onChange={(event) => setFollowup({ ...followup, note: event.target.value })} placeholder="What needs to happen next?"/></label></div>}</div>
      </div></fieldset>
    </div><NotePreview text={text} onCopy={() => copy("Call Notes", text, false)}/></div>
    <CardActions onCopy={() => copy("Call Notes", text, false)} onReset={reset}/>
  </ToolCard>;
}

function FilterCard({ filter, setFilter, text, copy, fold, toggle }) {
  const selected = Object.entries(filter.selected).filter(([, quantity]) => quantity > 0);
  const results = FILTER_SKUS.filter((sku) => sku.includes(filter.search.toUpperCase())).slice(0, 9);
  const add = (sku) => setFilter({ ...filter, search: "", selected: { ...filter.selected, [sku]: (filter.selected[sku] || 0) + 1 } });
  const quantity = (sku, amount) => setFilter({ ...filter, selected: { ...filter.selected, [sku]: Math.max(0, (filter.selected[sku] || 0) + amount) } });
  const remove = (sku) => { const selectedSkus = { ...filter.selected }; delete selectedSkus[sku]; setFilter({ ...filter, selected: selectedSkus }); };
  const [showResults, setShowResults] = useState(true);
  const picker = useRef(null); const inputId = useId(); const resultsId = useId();
  useEffect(() => {
    const outside = (event) => { if (!picker.current?.contains(event.target)) setShowResults(false); };
    document.addEventListener("pointerdown", outside);
    return () => document.removeEventListener("pointerdown", outside);
  }, []);
  return <ToolCard id="tool-filter" title="Swapped Filter Subscription" icon="package" open={fold} onToggle={toggle}>
    <div className="stack-fields"><label>Reason<select value={filter.reason} onChange={(event) => setFilter({ ...filter, reason: event.target.value })}><option>Swapped Filter</option><option>Wrong Filter Received</option><option>Variant Error</option><option>Filter Variant Request</option></select></label>
      <div className="sku-field"><label htmlFor={inputId}>Filter Model(s)</label><div ref={picker} className="sku-picker" onKeyDown={(event) => { if (event.key === "Escape") { setShowResults(false); picker.current.querySelector("input").focus(); setShowResults(false); } }}>
        <div className="input-with-icon"><Icon name="search"/><input id={inputId} autoComplete="off" aria-controls={resultsId} aria-expanded={Boolean(filter.search && showResults)} value={filter.search} onFocus={() => setShowResults(true)} onChange={(event) => { setFilter({ ...filter, search: event.target.value }); setShowResults(true); }} onKeyDown={(event) => { if (event.key === "ArrowDown" && showResults && filter.search) { event.preventDefault(); picker.current.querySelector(".sku-results button")?.focus(); } }} placeholder="Search filter SKU…"/></div>
        {filter.search && showResults && <div id={resultsId} className="sku-results" role="group" aria-label="Matching filter SKUs">{results.length ? results.map((sku) => <button key={sku} onClick={() => add(sku)} aria-label={`Add ${sku}`}><span>{sku}</span><Icon name="plus" size={16}/></button>) : <p role="status">No matching SKU. Try a model like MA-50.</p>}</div>}
      </div></div>
      {selected.length > 0 && <div className="sku-chips" aria-label="Selected filter quantities">{selected.map(([sku, amount]) => <div key={sku} className="sku-chip"><b>{sku}</b><span><button aria-label={`Decrease ${sku}`} onClick={() => quantity(sku, -1)}>−</button><output aria-label={`${sku} quantity`}>{amount}</output><button aria-label={`Increase ${sku}`} onClick={() => quantity(sku, 1)}>+</button><button aria-label={`Remove ${sku}`} onClick={() => remove(sku)}><Icon name="close" size={14}/></button></span></div>)}</div>}
      <label>Additional Notes<textarea rows="3" value={filter.notes} onChange={(event) => setFilter({ ...filter, notes: event.target.value })} placeholder="Add any supporting details…"/></label>
    </div><CardActions preview={text} onCopy={() => copy("Swapped Filter Subscription", text)} onReset={() => setFilter(blankFilter)}/>
  </ToolCard>;
}

function OrderCard({ order, setOrder, text, codeText, copy, fold, toggle }) {
  const code = (ORDER_CODES[order.category] || []).find(([value]) => value === order.reason) || ["", ""];
  const update = (field, value) => setOrder({ ...order, [field]: value });
  return <ToolCard id="tool-order" title="Order Codes / Replacement" icon="tag" open={fold} onToggle={toggle}><div className="field-layout compact-fields">{CASE_FIELDS.slice(0, 3).map((field) => <label key={field}>{field}<input value={order[field]} onChange={(event) => update(field, event.target.value)}/></label>)}<label className="span-all">Issue<textarea rows="2" value={order.Issue} onChange={(event) => update("Issue", event.target.value)} placeholder="Describe the issue manually..."/></label><label className="span-all">Resolution<textarea rows="2" value={order.Resolution} onChange={(event) => update("Resolution", event.target.value)} placeholder="Describe the resolution manually..."/></label><label>Category<select value={order.category} onChange={(event) => { const category = event.target.value; setOrder({ ...order, category, reason: ORDER_CODES[category][0][0] }); }}>{Object.keys(ORDER_CODES).map((category) => <option key={category}>{category}</option>)}</select></label><label>Reason Code<select value={order.reason} onChange={(event) => update("reason", event.target.value)}>{(ORDER_CODES[order.category] || []).map(([value]) => <option key={value} value={value}>{value.replaceAll("XXXXXX", order["Order ID"] || "XXXXXX")}</option>)}</select></label><label className="span-all">Description<input value={code[1]} readOnly/></label>{order.category === "Amazon" && order.reason.includes("Stuck Order") && <p className="inline-notice span-all"><Icon name="alert"/>For unfulfilled Medify Air MCF orders only. Cancel both corresponding orders first; ask a lead if unsure.</p>}</div><CardActions preview={text} onCopy={() => copy("Order Codes / Replacement", text)} onReset={() => setOrder(blankOrder)} extra={<button className="secondary-button copy-code" onClick={() => copy("Replacement Code", codeText)}><Icon name="copy"/>Copy Code</button>}/></ToolCard>;
}

function ClaimCard({ claim, setClaim, text, copy, fold, toggle }) {
  const update = (field, value) => setClaim({ ...claim, [field]: value });
  return <ToolCard id="tool-claim" title="UPS Claim" icon="truck" open={fold} onToggle={toggle}><div className="field-layout claim-fields"><label>Claim Number<input value={claim["Claim Number"]} onChange={(event) => update("Claim Number", event.target.value)}/></label><label>Tracking Number<input value={claim["Tracking Number"]} onChange={(event) => update("Tracking Number", event.target.value)}/></label><label>Claim Status<select value={claim["Claim Status"]} onChange={(event) => update("Claim Status", event.target.value)}>{CLAIM_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label></div><label className="invoice-check"><input type="checkbox" checked={claim.invoice} onChange={(event) => update("invoice", event.target.checked)}/><span><Icon name="check"/>Uploaded Invoice</span></label><CardActions preview={text} onCopy={() => copy("UPS Claim", text)} onReset={() => setClaim(blankClaim)}/></ToolCard>;
}

function GeneralCard({ general, setGeneral, text, copy, fold, toggle }) {
  const update = (field, value) => setGeneral({ ...general, [field]: value });
  return <ToolCard id="tool-general" title="Email / General Case Notes" icon="mail" open={fold} onToggle={toggle}><div className="template-picker"><label>Saved template<select defaultValue="" onChange={(event) => { if (event.target.value) setGeneral({ ...general, ...EMAIL_TEMPLATES[event.target.value] }); event.target.value = ""; }}><option value="">Select a starting template…</option>{Object.keys(EMAIL_TEMPLATES).map((name) => <option key={name}>{name}</option>)}</select></label><small>Templates are a starting point. You can edit every field.</small></div><div className="field-layout compact-fields">{CASE_FIELDS.slice(0, 3).map((field) => <label key={field}>{field}<input value={general[field]} onChange={(event) => update(field, event.target.value)}/></label>)}<label className="span-all">Issue<textarea rows="3" value={general.Issue} onChange={(event) => update("Issue", event.target.value)} placeholder="Write the issue manually..."/></label><label className="span-all">Resolution<textarea rows="3" value={general.Resolution} onChange={(event) => update("Resolution", event.target.value)} placeholder="Write the resolution manually..."/></label></div><CardActions preview={text} onCopy={() => copy("Email / General Case Notes", text)} onReset={() => setGeneral(BLANK_CASE)}/></ToolCard>;
}

function RecentMenu({ items, onCopy, onClose }) {
  const ref = useRef(null); const closeRef = useRef(onClose); closeRef.current = onClose;
  useEffect(() => {
    const trigger = document.getElementById("recent-trigger");
    ref.current?.querySelector("button")?.focus();
    const outside = (event) => { if (!ref.current?.contains(event.target) && !trigger?.contains(event.target)) closeRef.current(); };
    const escape = (event) => { if (event.key === "Escape") { closeRef.current(); trigger?.focus(); } };
    document.addEventListener("pointerdown", outside); document.addEventListener("focusin", outside); document.addEventListener("keydown", escape);
    return () => { document.removeEventListener("pointerdown", outside); document.removeEventListener("focusin", outside); document.removeEventListener("keydown", escape); };
  }, []);
  return <div id="recent-notes" ref={ref} role="dialog" aria-label="Recent utility notes" className="recent-menu">
    <header><div><strong>Recent utility notes</strong><small>Select a note to copy it again.</small></div><button className="icon-button" aria-label="Close recent notes" onClick={() => { onClose(); document.getElementById("recent-trigger")?.focus(); }}><Icon name="close"/></button></header>
    <div className="recent-items">{items.length ? items.map((item) => <button key={item.id} onClick={() => onCopy(item.title, item.text, false)}><span><b>{item.title}</b><small>{new Date(item.at).toLocaleString([], { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</small></span><Icon name="copy"/></button>) : <p className="empty-state">Copy a utility note to find it here later.</p>}</div>
  </div>;
}

function WorkDesk({ state }) {
  const { call, setCall, followup, setFollowup, filter, setFilter, order, setOrder, claim, setClaim, general, setGeneral, agent, running, seconds, startTimer, stopTimer, newCall, copy, folds, setFolds } = state;
  const callText = buildCallNote(call, agent);
  const orderCode = (ORDER_CODES[order.category] || []).find(([value]) => value === order.reason) || ["", ""];
  return <section className="workdesk-page" aria-label="WorkDesk">
    <h1 className="sr-only">WorkDesk</h1>
    <CallTimer running={running} seconds={seconds} onStart={startTimer} onStop={stopTimer} onNew={newCall}/>
    <div className="workspace-grid">
      <div className="work-column main-work-column"><CallNotes call={call} setCall={setCall} followup={followup} setFollowup={setFollowup} text={callText} copy={copy} reset={newCall} fold={folds.call} toggle={() => setFolds({ ...folds, call: !folds.call })}/><ClaimCard claim={claim} setClaim={setClaim} text={buildClaimNote(claim, agent)} copy={copy} fold={folds.claim} toggle={() => setFolds({ ...folds, claim: !folds.claim })}/></div>
      <div className="support-columns"><div className="support-grid">
        <div className="work-column"><FilterCard filter={filter} setFilter={setFilter} text={buildFilterNote(filter, agent)} copy={copy} fold={folds.filter} toggle={() => setFolds({ ...folds, filter: !folds.filter })}/></div>
        <div className="work-column"><OrderCard order={order} setOrder={setOrder} text={buildOrderNote(order, orderCode, agent)} codeText={replacementCode(order.category, orderCode[0], order["Order ID"])} copy={copy} fold={folds.order} toggle={() => setFolds({ ...folds, order: !folds.order })}/><GeneralCard general={general} setGeneral={setGeneral} text={buildNote(general, agent)} copy={copy} fold={folds.general} toggle={() => setFolds({ ...folds, general: !folds.general })}/></div>
      </div></div>
    </div>
  </section>;
}

function TrendChart({ points }) {
  const max = Math.max(...points.map((point) => point.value), 1);
  const coordinates = points.map((point, index) => `${(index / Math.max(points.length - 1, 1)) * 100},${88 - (point.value / max) * 72}`).join(" ");
  return <div className="trend-chart">
    <div className="trend-axis" aria-hidden="true"><span>{max}</span><span>0</span></div>
    <div className="trend-plot"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Call volume trend"><path className="trend-grid" d="M0 88H100M0 52H100M0 16H100"/><polyline className="trend-line" points={coordinates}/></svg>
      {points.map((point, index) => point.value > 0 && <button type="button" className="trend-point" key={point.label} style={{ left: `${(index / Math.max(points.length - 1, 1)) * 100}%`, top: `${88 - (point.value / max) * 72}%` }} aria-label={`${point.label}: ${point.value} calls`}><span>{point.label} · {point.value} calls</span></button>)}
      <ul className="sr-only" aria-label="Call volume data">{points.map(point => <li key={point.label}>{point.label}: {point.value} calls</li>)}</ul>
    </div><div className="trend-labels"><span>{points[0]?.label}</span><span>{points[Math.floor(points.length / 2)]?.label}</span><span>{points.at(-1)?.label}</span></div>
  </div>;
}

function ReportRow({ report, onCopy, onEdit, onDelete }) {
  const fields = report.fields || {}; const follow = followupState(report);
  return <details className="report-row"><summary>
    <span className="report-identity"><span className="report-avatar">{fields["Agent Initials"] || "?"}</span><span className="report-person"><b>{fields["Spoke With"] || "Unnamed caller"}</b><small>{fields["Name on the Account"] || "No account name"} · {fields["Order Num"] || "No order"}</small></span></span>
    <span className="report-tags"><span className="driver-pill">{report.callDriver || detectCallDriver(fields)}</span>{follow !== "none" && <span className={`followup-pill ${follow}`}>{follow === "today" ? "Due today" : follow === "overdue" ? "Overdue" : "Follow-up"}</span>}</span>
    <time className="report-time" dateTime={new Date(report.stop || report.start).toISOString()}>{new Date(report.stop || report.start).toLocaleString([], { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</time><strong className="report-duration">{formatDuration(report.seconds)}</strong><Icon name="chevron" className="record-chevron"/>
  </summary><div className="report-expanded">
    <div className="report-info-grid">{[["Order", fields["Order Num"]], ["Email", fields["Email Address"]], ["Contact", fields["Contact #"]], ["AC Call ID", fields["AC Call ID"]]].map(([label, value]) => <div key={label}><small>{label}</small><b>{value || "Not provided"}</b></div>)}</div>
    <div className="report-copy"><small>Reason for Calling</small><p>{fields["Reason for Calling"] || "Not provided"}</p><small>ACTION TAKEN</small><p>{fields["ACTION TAKEN"] || "Not provided"}</p>{report.followUpNeeded && <><small>Follow-up · {report.followUpDate || "No date"}</small><p>{report.followUpNote || "No note"}</p></>}</div>
    <div className="report-buttons"><button className="secondary-button" onClick={() => onCopy("Call Report", buildCallNote(fields, fields["Agent Initials"]), false)}><Icon name="copy"/>Copy</button><button className="secondary-button" onClick={() => onEdit(report)}><Icon name="edit"/>Edit</button><button className="danger-button" onClick={() => onDelete(report)}><Icon name="trash"/>Delete</button></div>
  </div></details>;
}

function EditReport({ report, onClose, onSave }) {
  const [minutes, setMinutes] = useState(String(Math.floor((report.seconds || 0) / 60))); const [seconds, setSeconds] = useState(String((report.seconds || 0) % 60)); const [followDate, setFollowDate] = useState(report.followUpDate || ""); const [followNote, setFollowNote] = useState(report.followUpNote || ""); const [needed, setNeeded] = useState(Boolean(report.followUpNeeded));
  const save = () => { const minuteValue = Math.max(0, Number(minutes) || 0); const secondValue = Math.min(59, Math.max(0, Number(seconds) || 0)); onSave({ seconds: minuteValue * 60 + secondValue, followUpNeeded: needed, followUpDate: followDate, followUpNote: followNote }); };
  return <Dialog title="Edit call report" eyebrow="Saved report" onClose={onClose} className="edit-modal" footer={<><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={save}>Save changes</button></>}>
    <p className="dialog-context">{report.fields?.["Spoke With"] || "Unnamed caller"}</p>
    <fieldset className="form-group"><legend>Call duration</legend><div className="duration-fields"><label>Minutes<input min="0" type="number" value={minutes} onChange={(event) => setMinutes(event.target.value)}/></label><label>Seconds<input min="0" max="59" type="number" value={seconds} onChange={(event) => setSeconds(event.target.value)} aria-describedby="seconds-hint"/></label></div><small id="seconds-hint" className="field-hint">Seconds: 0–59</small></fieldset>
    <div className={`followup-box ${needed ? "is-needed" : ""}`}><label className="check-label"><input type="checkbox" checked={needed} onChange={(event) => setNeeded(event.target.checked)}/><span>Follow-up needed</span></label>{needed && <div className="stack-fields unpadded"><label>Follow-up date<input type="date" value={followDate} onChange={(event) => setFollowDate(event.target.value)}/></label><label>Follow-up note<textarea rows="4" value={followNote} onChange={(event) => setFollowNote(event.target.value)}/></label></div>}</div>
  </Dialog>;
}

function Reports({ reports, copy, updateReport, deleteReport }) {
  const [period, setPeriod] = useState("Daily"); const [query, setQuery] = useState(""); const [driver, setDriver] = useState("All"); const [agent, setAgent] = useState("All"); const [follow, setFollow] = useState("All"); const [edit, setEdit] = useState(null);
  const initials = [...new Set(reports.map((item) => item.fields?.["Agent Initials"]).filter(Boolean))].sort(); const drivers = [...new Set(reports.map((item) => item.callDriver || detectCallDriver(item.fields)))].sort();
  const baseFiltered = reports.filter((report) => { const fields = report.fields || {}; const haystack = [fields["Spoke With"], fields["Name on the Account"], fields["Order Num"], fields["Email Address"], fields["AC Call ID"]].join(" ").toLowerCase(); const state = followupState(report); return (!query || haystack.includes(query.toLowerCase())) && (driver === "All" || (report.callDriver || detectCallDriver(fields)) === driver) && (agent === "All" || fields["Agent Initials"] === agent) && (follow === "All" || state === follow); });
  const periodBuckets = [...new Set(baseFiltered.map((report) => periodKey(report, period)))].sort((a, b) => b.localeCompare(a)); const selectedPeriod = periodBuckets[0] || ""; const periodReports = selectedPeriod ? baseFiltered.filter((report) => periodKey(report, period) === selectedPeriod) : []; const filtered = periodReports;
  const totalSeconds = periodReports.reduce((total, report) => total + (report.seconds || 0), 0); const topDriver = drivers.map((name) => [name, periodReports.filter((report) => (report.callDriver || detectCallDriver(report.fields)) === name).length]).sort((a, b) => b[1] - a[1])[0]?.[0] || "—"; const todayFollowups = periodReports.filter((report) => followupState(report) === "today").length;
  const grouped = periodReports.reduce((groups, report) => { const key = periodKey(report, period); (groups[key] ||= []).push(report); return groups; }, {});
  return <section className="reports-page" aria-label="Call Reports">
    <div className="analytics-heading"><div><p className="eyebrow">Reports</p><h1>Call Reports</h1><p>Review saved calls and keep follow-ups in view.</p></div><PeriodTabs period={period} setPeriod={setPeriod}/></div>
    <div className="period-context"><span><Icon name="calendar"/><strong>{period}</strong><span>{selectedPeriod || "No matching period"}</span></span><small>Latest matching period · filters apply to all metrics and records</small></div>
    <div className="report-kpis"><article><small>Total calls</small><b>{filtered.length}</b><span>in this period</span></article><article><small>Total duration</small><b>{formatDuration(totalSeconds)}</b><span>across saved calls</span></article><article><small>Average call</small><b>{formatDuration(filtered.length ? totalSeconds / filtered.length : 0)}</b><span>per saved call</span></article><article><small>Top call driver</small><b className="kpi-text">{filtered.length ? topDriver : "—"}</b><span>{todayFollowups} follow-up{todayFollowups === 1 ? "" : "s"} due today</span></article></div>
    <div className="report-analysis"><article className="trend-panel"><header><div><h2>Call volume</h2><p>Saved calls in this {period.toLowerCase()} view</p></div><span className="chart-key"><i/>Calls</span></header><TrendChart points={trendPoints(filtered, period)}/></article>
      <article className="followup-panel"><header><h2>Follow-ups</h2><span className="count-badge">{filtered.filter((item) => followupState(item) !== "none").length}</span></header><div className="followup-list">{filtered.filter((item) => followupState(item) !== "none").slice(0, 4).map((item) => <button key={item.id} className="followup-item" onClick={() => setEdit(item)} aria-label={`Edit follow-up for ${item.fields?.["Spoke With"] || "Unnamed caller"}`}><span className="followup-item-heading"><b>{item.fields?.["Spoke With"] || "Unnamed caller"}</b><span className={`followup-pill ${followupState(item)}`}>{followupState(item) === "today" ? "Due today" : followupState(item) === "overdue" ? "Overdue" : "Upcoming"}</span></span><small>{item.followUpDate || item.fields?.["Follow-up Date"] || "No date"} · {item.followUpNote || item.fields?.["Follow-up Note"] || "No note"}</small></button>)}{!filtered.some((item) => followupState(item) !== "none") && <p className="empty-state"><Icon name="calendar"/>No follow-ups in this view.</p>}</div>{filtered.filter((item) => followupState(item) !== "none").length > 4 && <p className="field-hint">Showing the first 4. Use the Follow-up filter to review all matching records.</p>}</article>
    </div>
    <div className="records-heading"><h2>Saved call reports</h2><span>{filtered.length} call{filtered.length === 1 ? "" : "s"}</span></div>
    <div className="report-controls"><label className="report-search-label">Search reports<div className="search-control"><Icon name="search"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, account, order, email or AC Call ID…"/></div></label><label>Call driver<select value={driver} onChange={(event) => setDriver(event.target.value)}><option value="All">All call drivers</option>{drivers.map((value) => <option key={value}>{value}</option>)}</select></label><label>Agent initials<select value={agent} onChange={(event) => setAgent(event.target.value)}><option value="All">All agents</option>{initials.map((value) => <option key={value}>{value}</option>)}</select></label><label>Follow-up<select value={follow} onChange={(event) => setFollow(event.target.value)}><option value="All">All follow-ups</option><option value="today">Due today</option><option value="overdue">Overdue</option><option value="upcoming">Upcoming</option></select></label></div>
    <div className="report-table"><header aria-hidden="true"><span>Caller &amp; account</span><span>Driver &amp; follow-up</span><span>Saved at</span><span>Duration</span><span/></header>{Object.entries(grouped).sort(([a], [b]) => b.localeCompare(a)).map(([key, rows]) => <section key={key} className="report-period"><h2>{key}<small>{rows.length} call{rows.length === 1 ? "" : "s"}</small></h2>{rows.map((report) => <ReportRow key={report.id} report={report} onCopy={copy} onEdit={setEdit} onDelete={deleteReport}/>)}</section>)}{!filtered.length && <div className="empty-state"><Icon name="note" size={26}/><strong>{reports.length ? "No matching call reports" : "No saved calls yet"}</strong><p>{reports.length ? "Try another search or filter." : "In WorkDesk, start the timer, then choose Stop & Save to create a report."}</p></div>}</div>
    {edit && <EditReport report={edit} onClose={() => setEdit(null)} onSave={(fields) => { updateReport(edit, fields); setEdit(null); }}/>}
  </section>;
}

function Drivers({ reports }) {
  const [period, setPeriod] = useState("Monthly"); const groups = reports.reduce((result, report) => { const key = periodKey(report, period); (result[key] ||= []).push(report); return result; }, {});
  return <section className="drivers-page"><div className="analytics-heading"><div><p className="eyebrow">Call insights</p><h1>Call Drivers</h1><p>Detected from Reason for Calling and ACTION TAKEN when a call is saved.</p></div><PeriodTabs period={period} setPeriod={setPeriod} label="Call driver period"/></div>{Object.entries(groups).sort(([a], [b]) => b.localeCompare(a)).map(([key, rows]) => { const drivers = rows.reduce((result, report) => { const name = report.callDriver || detectCallDriver(report.fields); (result[name] ||= []).push(report); return result; }, {}); const max = Math.max(...Object.values(drivers).map((items) => items.length), 1); return <section className="driver-panel" key={key}><header><h2>{key}</h2><span className="count-badge">{rows.length} calls</span></header>{Object.entries(drivers).sort(([, a], [, b]) => b.length - a.length).map(([name, items]) => <div className="driver-bar" key={name}><div><b>{name}</b><small>{items.length} call{items.length === 1 ? "" : "s"} · {formatDuration(items.reduce((total, item) => total + item.seconds, 0))}</small></div><span><i style={{ width: `${(items.length / max) * 100}%` }}/><b>{items.length}</b></span></div>)}</section>; })}{!reports.length && <p className="empty-state">Call driver insights appear after you save a call.</p>}</section>;
}

function Settings({ profile, initials, setInitials, close, toast }) {
  const [newInitial, setNewInitial] = useState(""); const [code, setCode] = useState(""); const [assigned, setAssigned] = useState("JA"); const [invites, setInvites] = useState([]); const [message, setMessage] = useState("");
  const active = initials.filter((item) => item.active).map((item) => item.initials);
  useEffect(() => { if (profile.role === "creator") supabase.from("medify_invite_codes").select("id,code_value,assigned_initials,used_at,revoked_at,deactivated_at,created_at").order("created_at", { ascending: false }).then(({ data }) => setInvites(data || [])); }, [profile.role]);
  const show = (value) => { setMessage(value); toast(value); };
  const addInitial = async () => { const value = newInitial.trim().toUpperCase(); if (!/^[A-Z0-9]{1,4}$/.test(value)) return show("Use 1–4 letters or numbers only."); const { error } = await supabase.rpc("medify_add_agent_initial", { p_initials: value }); if (error) return show(error.message); setInitials([...initials, { initials: value, active: true }].sort((a, b) => a.initials.localeCompare(b.initials))); setNewInitial(""); show(`${value} added.`); };
  const setActive = async (item) => { const { error } = await supabase.rpc("medify_set_agent_initial_active", { p_initials: item.initials, p_active: !item.active }); if (error) return show(error.message); setInitials(initials.map((row) => row.initials === item.initials ? { ...row, active: !row.active } : row)); };
  const deleteInitial = async (initial) => { if (!window.confirm(`Delete ${initial}? This cannot remove users or historical reports.`)) return; const { error } = await supabase.rpc("medify_delete_agent_initial", { p_initials: initial }); if (error) return show(error.message); setInitials(initials.filter((item) => item.initials !== initial)); show(`${initial} deleted.`); };
  const createInvite = async () => { if (code.trim().length < 8) return show("Use an access code with at least 8 characters."); const { data, error } = await supabase.rpc("medify_create_invite", { p_code: code.trim(), p_initials: assigned }); if (error) return show(error.message); setInvites([{ id: data, code_value: code.trim(), assigned_initials: assigned, created_at: new Date().toISOString() }, ...invites]); setCode(""); show("One-time access code created."); };
  const inviteAction = async (id, action) => { const { error } = await supabase.rpc(action, { p_id: id }); if (error) return show(error.message); const field = action === "medify_revoke_invite" ? "revoked_at" : action === "medify_deactivate_invite" ? "deactivated_at" : "deleted"; setInvites(invites.filter((item) => field !== "deleted" || item.id !== id).map((item) => item.id === id ? { ...item, [field]: new Date().toISOString() } : item)); show("Access code updated."); };
  return <Dialog title="Workspace settings" eyebrow="Personal Notes" onClose={close} className="settings-drawer"><section><h3>Account</h3><p>Signed in as <b>{profile.initials}</b></p><button className="secondary-button" onClick={() => supabase.auth.signOut()}>Sign out</button></section>{profile.role === "creator" && <section className="team-settings"><h3>Team Management</h3><p>Creator-only controls for access codes and agent initials.</p><div className="settings-block"><h4>Agent Initials</h4>{initials.map((item) => <div className="initial-item" key={item.initials}><b>{item.initials}</b><span className={item.active ? "status-active" : "status-inactive"}>{item.active ? "Active" : "Inactive"}</span>{!["JA", "FA"].includes(item.initials) && <><button className="text-button" onClick={() => setActive(item)}>{item.active ? "Deactivate" : "Activate"}</button><button className="danger-button" onClick={() => deleteInitial(item.initials)}>Delete</button></>}</div>)}<div className="inline-add"><input aria-label="New agent initials" maxLength="4" value={newInitial} onChange={(event) => setNewInitial(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""))} placeholder="CJ"/><button className="outline-button" onClick={addInitial}><Icon name="plus"/>Add Initials</button></div></div><div className="settings-block"><h4>New access code</h4><label>Private code<input value={code} onChange={(event) => setCode(event.target.value)} placeholder="At least 8 characters"/></label><label>Assign initials<select value={assigned} onChange={(event) => setAssigned(event.target.value)}>{active.map((value) => <option key={value}>{value}</option>)}</select></label><button className="primary-button" onClick={createInvite}>Create one-time code</button></div>{message && <p role="status" className="settings-message">{message}</p>}<div className="settings-block"><h4>Access codes</h4>{invites.map((item) => <div className="invite-item" key={item.id}><span><b>{item.used_at ? "Used" : item.revoked_at ? "Revoked" : item.deactivated_at ? "Deactivated" : "Active"}</b><small>{item.assigned_initials || "—"} · {item.code_value || "Code hidden"}</small></span><div>{!item.used_at && !item.revoked_at && !item.deactivated_at && <><button className="text-button" onClick={() => inviteAction(item.id, "medify_deactivate_invite")}>Deactivate</button><button className="text-button" onClick={() => inviteAction(item.id, "medify_revoke_invite")}>Revoke</button></>}<button className="danger-button" onClick={() => { if (window.confirm("Delete this access code?")) inviteAction(item.id, "medify_delete_invite"); }}>Delete</button></div></div>)}{!invites.length && <p className="quiet">No access codes created yet.</p>}</div></section>}</Dialog>;
}

function AuthScreen({ auth, setAuth, mode, setMode, error, onSubmit, initials }) {
  const [pending, setPending] = useState(false);
  return <main className="auth-page"><section className="auth-card">
    <header className="auth-brand"><img src={`${import.meta.env.BASE_URL}personal-notes-avatar.png`} alt="Personal Notes avatar"/><div><strong>Personal Notes</strong><span>Support workspace</span></div></header>
    <div className="auth-content"><p className="eyebrow">{mode === "login" ? "Welcome back" : "Account activation"}</p><h1>{mode === "login" ? "Sign in to your workspace" : "Set up your workspace"}</h1><p>{mode === "login" ? "Access your support tools and saved call reports." : "Use your one-time access code and assigned initials to activate your account."}</p>
      <form onSubmit={async (event) => { setPending(true); try { await onSubmit(event); } finally { setPending(false); } }} aria-busy={pending}>
        <label>Username<input required autoComplete="username" autoCapitalize="none" spellCheck="false" value={auth.username} onChange={(event) => setAuth({ ...auth, username: event.target.value })}/></label>
        <label>PIN / passcode<input required minLength="8" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} aria-describedby="passcode-hint" value={auth.password} onChange={(event) => setAuth({ ...auth, password: event.target.value })}/></label><small id="passcode-hint" className="field-hint">At least 8 characters</small>
        {mode === "activate" && <><label>One-time access code<input required autoComplete="off" value={auth.code} onChange={(event) => setAuth({ ...auth, code: event.target.value })}/></label><label>Assigned initials<select value={auth.initials} onChange={(event) => setAuth({ ...auth, initials: event.target.value })}>{initials.map((value) => <option key={value}>{value}</option>)}</select></label></>}
        {error && <p className="auth-error" role="alert"><Icon name="alert"/>{error}</p>}
        <button className="primary-button" disabled={pending}>{pending ? (mode === "login" ? "Signing in…" : "Activating…") : (mode === "login" ? "Sign in" : "Activate account")}</button>
      </form>
      <button className="text-button auth-switch" disabled={pending} onClick={() => setMode(mode === "login" ? "activate" : "login")}>{mode === "login" ? "I have an access code" : "Already activated? Sign in"}</button>
    </div>
  </section></main>;
}

export default function App() {
  const [session, setSession] = useState(null); const [profile, setProfile] = useState(null); const [loading, setLoading] = useState(true); const [view, setView] = useState("workdesk"); const [settingsOpen, setSettingsOpen] = useState(false); const [recentOpen, setRecentOpen] = useState(false); const [toast, setToast] = useState(""); const [authError, setAuthError] = useState(""); const [mode, setMode] = useState("login"); const [auth, setAuth] = useState({ username: "", password: "", code: "", initials: "JA" });
  const [initials, setInitials] = useState([{ initials: "JA", active: true }, { initials: "FA", active: true }]); const [reports, setReports] = useState(() => readStorage("medify-call-reports", [])); const [recent, setRecent] = useState(() => readStorage("medify-workdesk-recent", [])); const [call, setCall] = useState(() => readStorage("medify-active-call-draft", {}).fields || BLANK_CALL); const [followup, setFollowup] = useState(() => readStorage("medify-active-call-draft", {}).followup || { needed: false, date: "", note: "" }); const [startedAt, setStartedAt] = useState(() => readStorage("medify-active-call-draft", {}).startedAt || null); const [now, setNow] = useState(Date.now());
  const [filter, setFilter] = useState(() => readStorage("medify-workdesk-filter-draft", blankFilter)); const [order, setOrder] = useState(() => readStorage("medify-workdesk-order-draft", blankOrder)); const [claim, setClaim] = useState(() => readStorage("medify-workdesk-claim-draft", blankClaim)); const [general, setGeneral] = useState(() => readStorage("medify-workdesk-general-draft", BLANK_CASE)); const [folds, setFolds] = useState({ call: true, filter: true, order: true, claim: true, general: true });
  const agent = profile?.initials || "JA"; const running = Boolean(startedAt); const seconds = running ? Math.floor((now - startedAt) / 1000) : 0; const activeInitials = initials.filter((item) => item.active).map((item) => item.initials);
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false); }); const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, nextSession) => { setSession(nextSession); if (!nextSession) setProfile(null); }); return () => subscription.unsubscribe(); }, []);
  useEffect(() => { if (!session?.user?.id) return; supabase.from("medify_profiles").select("*").eq("id", session.user.id).single().then(({ data, error }) => { if (error) setAuthError("Your account has not been activated with a valid access code yet."); else setProfile(data); }); }, [session]);
  useEffect(() => { if (!profile?.id) return; supabase.from("medify_call_reports").select("*").order("stopped_at", { ascending: false }).then(({ data, error }) => { if (!error) setReports((data || []).map((item) => ({ id: item.id, remote: true, start: new Date(item.started_at).getTime(), stop: new Date(item.stopped_at).getTime(), seconds: item.duration_seconds, fields: item.note_fields || {}, callDriver: item.call_driver, followUpNeeded: item.follow_up_needed ?? item.note_fields?.["Follow-up Needed"] === "Yes", followUpDate: item.follow_up_date ?? item.note_fields?.["Follow-up Date"] ?? "", followUpNote: item.follow_up_note ?? item.note_fields?.["Follow-up Note"] ?? "" }))); }); supabase.from("medify_agent_initials").select("initials,active").order("initials").then(({ data, error }) => { if (!error && data?.length) setInitials(data); }); }, [profile]);
  useEffect(() => { if (!running) return undefined; const interval = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(interval); }, [running]); useEffect(() => { if (!toast) return undefined; const timeout = setTimeout(() => setToast(""), 2600); return () => clearTimeout(timeout); }, [toast]);
  useEffect(() => { localStorage.setItem("medify-active-call-draft", JSON.stringify({ fields: call, followup, startedAt })); }, [call, followup, startedAt]); useEffect(() => localStorage.setItem("medify-call-reports", JSON.stringify(reports)), [reports]); useEffect(() => localStorage.setItem("medify-workdesk-filter-draft", JSON.stringify(filter)), [filter]); useEffect(() => localStorage.setItem("medify-workdesk-order-draft", JSON.stringify(order)), [order]); useEffect(() => localStorage.setItem("medify-workdesk-claim-draft", JSON.stringify(claim)), [claim]); useEffect(() => localStorage.setItem("medify-workdesk-general-draft", JSON.stringify(general)), [general]);
  const notify = (message) => setToast(message);
  const copy = async (title, text, saveRecent = true) => { try { await navigator.clipboard.writeText(text); if (saveRecent) { const item = { id: crypto.randomUUID(), title, text, at: Date.now() }; setRecent((items) => { const next = [item, ...items].slice(0, 20); localStorage.setItem("medify-workdesk-recent", JSON.stringify(next)); return next; }); } notify("Copied to clipboard."); } catch { notify("Copy was blocked. Select the preview text manually."); } };
  const newCall = () => { if (running && !window.confirm("Start a new call? The current unsaved timer will be cleared.")) return; setCall(BLANK_CALL); setFollowup({ needed: false, date: "", note: "" }); setStartedAt(null); localStorage.removeItem("medify-active-call-draft"); };
  const startTimer = () => { const value = Date.now(); setNow(value); setStartedAt(value); notify("Call timer started."); };
  const stopTimer = async () => { if (!running) return; const stop = Date.now(); const fields = { ...call, "Agent Initials": agent, "Follow-up Needed": followup.needed ? "Yes" : "No", "Follow-up Date": followup.date, "Follow-up Note": followup.note }; const report = { id: `local-${startedAt}-${stop}`, start: startedAt, stop, seconds: Math.floor((stop - startedAt) / 1000), fields, callDriver: detectCallDriver(call), followUpNeeded: followup.needed, followUpDate: followup.date, followUpNote: followup.note }; setStartedAt(null); setReports((items) => [report, ...items]); const base = { agent_id: profile.id, started_at: new Date(report.start).toISOString(), stopped_at: new Date(report.stop).toISOString(), duration_seconds: report.seconds, call_driver: report.callDriver, note_fields: fields }; let { data, error } = await supabase.from("medify_call_reports").insert({ ...base, follow_up_needed: followup.needed, follow_up_date: followup.date || null, follow_up_note: followup.note || null }).select().single(); if (error && /follow_up/i.test(error.message)) ({ data, error } = await supabase.from("medify_call_reports").insert(base).select().single()); if (error) notify(`Saved locally; online save failed: ${error.message}`); else { setReports((items) => items.map((item) => item.id === report.id ? { ...report, id: data.id, remote: true } : item)); notify("Call stopped and saved to Reports."); } };
  const updateReport = async (report, update) => { const next = { ...report, ...update, stop: report.start + update.seconds * 1000 }; setReports((items) => items.map((item) => item.id === report.id ? next : item)); if (report.remote) { const payload = { duration_seconds: update.seconds, stopped_at: new Date(next.stop).toISOString(), follow_up_needed: update.followUpNeeded, follow_up_date: update.followUpDate || null, follow_up_note: update.followUpNote || null }; let { error } = await supabase.from("medify_call_reports").update(payload).eq("id", report.id); if (error && /follow_up/i.test(error.message)) ({ error } = await supabase.from("medify_call_reports").update({ duration_seconds: update.seconds, stopped_at: new Date(next.stop).toISOString() }).eq("id", report.id)); if (error) notify(`Saved locally; online update failed: ${error.message}`); else notify("Report updated."); } };
  const deleteReport = async (report) => { if (!window.confirm("Delete this saved call report? This cannot be undone.")) return; setReports((items) => items.filter((item) => item.id !== report.id)); if (report.remote) { const { error } = await supabase.from("medify_call_reports").delete().eq("id", report.id); if (error) return notify(`Delete failed: ${error.message}`); } notify("Report deleted."); };
  const submitAuth = async (event) => { event.preventDefault(); setAuthError(""); try { const username = auth.username.trim().toLowerCase(); if (mode === "login") { const { error } = await supabase.auth.signInWithPassword({ email: usernameEmail(username), password: auth.password }); if (error) throw error; } else { const { data, error } = await supabase.auth.signUp({ email: usernameEmail(username), password: auth.password }); if (error) throw error; if (!data.session) throw Error("Email confirmation is enabled. Turn it off in Supabase Authentication > Providers > Email."); const { error: redeemError } = await supabase.rpc("medify_redeem_invite", { p_code: auth.code.trim(), p_username: username, p_initials: auth.initials }); if (redeemError) throw redeemError; } } catch (error) { setAuthError(error.message); } };
  const searchTools = (value) => { const query = value.toLowerCase(); if (!query) return; setView("workdesk"); const key = query.includes("claim") ? "claim" : query.includes("filter") ? "filter" : query.includes("replacement") || query.includes("order") ? "order" : query.includes("email") || query.includes("case") ? "general" : "call"; setFolds({ ...folds, [key]: true }); };
  if (loading) return <main className="loading-page" role="status"><Icon name="note" size={30}/><strong>Loading your workspace…</strong></main>;
  if (!session || !profile) return <AuthScreen auth={auth} setAuth={setAuth} mode={mode} setMode={setMode} error={authError} onSubmit={submitAuth} initials={activeInitials}/>;
  const nav = (id, label, icon) => <button aria-current={view === id ? "page" : undefined} className={view === id ? "active" : ""} onClick={() => setView(id)}><Icon name={icon}/>{label}</button>;
  return <main className="app-shell"><a className="skip-link" href="#workspace-content">Skip to workspace</a>
    <header className="site-header"><button className="brand-lockup" onClick={() => setView("workdesk")}><img src={`${import.meta.env.BASE_URL}personal-notes-avatar.png`} alt=""/><span><strong>Personal Notes</strong><small>Support workspace</small></span></button>
      <div className="global-search"><Icon name="search"/><input aria-label="Find a workspace tool" onChange={(event) => searchTools(event.target.value)} placeholder="Find a tool: call, filter, order, claim…" onKeyDown={(event) => {
        if (event.key !== "Enter" || !event.currentTarget.value) return;
        const query = event.currentTarget.value.toLowerCase();
        const key = query.includes("claim") ? "claim" : query.includes("filter") ? "filter" : query.includes("replacement") || query.includes("order") ? "order" : query.includes("email") || query.includes("case") ? "general" : "call";
        const target = document.getElementById(`tool-${key}`); target?.scrollIntoView({ block: "start" }); target?.querySelector("input, textarea, select")?.focus({ preventScroll: true });
      }}/><kbd aria-hidden="true">Enter</kbd></div>
      <div className="header-links"><div className="recent-wrap"><button id="recent-trigger" aria-expanded={recentOpen} aria-controls="recent-notes" aria-haspopup="dialog" onClick={() => setRecentOpen(!recentOpen)}><Icon name="clock"/><span>Recent</span></button>{recentOpen && <RecentMenu items={recent} onCopy={copy} onClose={() => setRecentOpen(false)}/>}</div><button aria-haspopup="dialog" onClick={() => { setRecentOpen(false); setSettingsOpen(true); }}><Icon name="settings"/><span>Settings</span></button><span className="user-avatar" title={`Signed in as ${agent}`} aria-label={`Signed in as ${agent}`}>{agent}</span></div>
    </header>
    <nav className="main-nav" aria-label="Main navigation">{nav("workdesk", "WorkDesk", "grid")}{nav("reports", "Reports", "chart")}{nav("drivers", "Call Drivers", "phone")}<span><Icon name="calendar"/>{new Date().toLocaleDateString([], { weekday: "short", month: "short", day: "numeric" })}<b>·</b>Support Team</span></nav>
    <div id="workspace-content" tabIndex="-1">{view === "workdesk" && <WorkDesk state={{ call, setCall, followup, setFollowup, filter, setFilter, order, setOrder, claim, setClaim, general, setGeneral, agent, running, seconds, startTimer, stopTimer, newCall, copy, folds, setFolds }}/>} {view === "reports" && <Reports reports={reports} copy={copy} updateReport={updateReport} deleteReport={deleteReport}/>} {view === "drivers" && <Drivers reports={reports}/>}</div>
    {settingsOpen && <Settings profile={profile} initials={initials} setInitials={setInitials} close={() => setSettingsOpen(false)} toast={notify}/>} {toast && <div className="toast" role="status"><Icon name={/failed|blocked|error/i.test(toast) ? "alert" : "check"}/><span>{toast}</span></div>}
  </main>;
}
