export const VERIFIED_ON = "July 23, 2026";
const ASSET_BASE = import.meta.env?.BASE_URL ?? "/";

export const products = [
  {
    id: "ma-22",
    model: "MA-22",
    revision: "Standard",
    status: "Active",
    finderEligible: true,
    coverage: 278,
    cadr: 74,
    cadrMetric: 126,
    dimensions: "15 H × 10 W × 10 D in",
    weight: "7 lb",
    wattage: "38 W",
    speeds: "3",
    controls: "Timer, three speeds, touch controls, child lock",
    filterLife: "2,000 hours (about 3–4 months)",
    filtration: "Pre-filter, HEPA, active carbon composite",
    sound: "Sleep 21.3; speeds 33.0 / 44.8 / 52.4 dBA",
    wheels: "No",
    warranty: "Limited lifetime; current terms and registration still apply",
    filter: "Use the exact current MA-22 replacement filter listed by Medify",
    reset: "Use the exact MA-22 manual procedure; do not generalize across models",
    image: `${ASSET_BASE}products/ma-22.png`,
    source: "https://medifyair.com/products/ma-22-air-purifier",
    sourceLabel: "Official MA-22 product page",
    summary: "Compact active model for smaller rooms, with a verified 278 sq ft 30-minute coverage value.",
    flags: []
  },
  {
    id: "ma-25",
    model: "MA-25",
    revision: "White · current",
    status: "Active",
    finderEligible: true,
    coverage: 413,
    cadr: 110,
    cadrMetric: 187,
    dimensions: "13.5 H × 8 W × 8 D in",
    weight: "7.3 lb",
    wattage: "28 W",
    speeds: "3",
    controls: "Timer, three speeds, filter indicator, touch controls, child lock, dimmer",
    filterLife: "2,500 hours (about 3–4 months)",
    filtration: "Pre-filter, HEPA, active carbon composite",
    sound: "19.8 / 37 / 49.3 dBA",
    wheels: "No",
    warranty: "Limited lifetime; current terms and registration still apply",
    filter: "Use the exact current MA-25 replacement filter listed by Medify",
    reset: "Use the exact MA-25 manual procedure",
    image: `${ASSET_BASE}products/ma-25.png`,
    source: "https://medifyair.com/products/medify-ma-25-air-purifier",
    sourceLabel: "Official MA-25 product page",
    summary: "Slim active model with an approved 413 sq ft sizing threshold.",
    flags: ["413 sq ft is the approved value; an older official card showed 423."]
  },
  {
    id: "ma-35",
    model: "MA-35",
    revision: "Wall-mount · current unit",
    status: "Active",
    finderEligible: true,
    coverage: 656,
    cadr: 173.2,
    cadrMetric: 294,
    dimensions: "15.6 H × 23.2 W × 3.9 D in",
    weight: "16 lb",
    wattage: "40 W",
    speeds: "3",
    controls: "Timer, three speeds, sleep, indicator, touch controls, child lock, optional ionizer",
    filterLife: "2,500 hours (about 3–4 months)",
    filtration: "Pre-filter, HEPA, active carbon composite",
    sound: "29 / 46.4 / 54.1 dBA",
    wheels: "No",
    warranty: "Limited lifetime; current terms and registration still apply",
    filter: "Use the exact current MA-35 replacement filter listed by Medify",
    reset: "Use the exact MA-35 unit manual; table-stand guidance is legacy",
    image: `${ASSET_BASE}products/ma-35.png`,
    source: "https://medifyair.com/products/ma-wm35",
    sourceLabel: "Official MA-35 product page",
    summary: "Low-profile wall-mount model with an approved 656 sq ft sizing threshold.",
    flags: ["656 sq ft is the approved value; an older manual index showed 640."]
  },
  {
    id: "ma-40",
    model: "MA-40",
    revision: "White · standard non-UV",
    status: "Active",
    finderEligible: true,
    coverage: 896,
    cadr: 239,
    cadrMetric: 406,
    dimensions: "22 H × 9.9 W × 10.9 D in",
    weight: "17.5 lb",
    wattage: "68 W",
    speeds: "3",
    controls: "Timer, three speeds, sleep, indicator, touch controls, child lock; no Auto mode",
    filterLife: "3,000 hours (about 4–5 months)",
    filtration: "Pre-filter, HEPA, active carbon composite",
    sound: "Sleep 40.5; speeds 40.5 / 50.3 / 53.3 dB",
    wheels: "No",
    warranty: "Limited lifetime; current terms and registration still apply",
    filter: "Use the exact standard MA-40 filter; verify variant before selection",
    reset: "Standard and UV variants have separate instructions",
    image: `${ASSET_BASE}products/ma-40.png`,
    source: "https://medifyair.com/products/medify-ma-40",
    sourceLabel: "Official MA-40 product page",
    summary: "Mid-size active model; this profile is for the white standard non-UV revision.",
    flags: ["Never transfer MA-40 UV instructions to this standard variant."]
  },
  {
    id: "ma-50",
    model: "MA-50",
    revision: "V3.0 · no UV",
    status: "Active",
    finderEligible: true,
    coverage: 1320,
    cadr: 352,
    cadrMetric: 598,
    dimensions: "21.18 H × 9.65 W × 9.65 D in",
    weight: "10 lb",
    wattage: "70 W",
    speeds: "4",
    controls: "Timer, four speeds, sleep, indicator, touch controls, child lock, dimmer",
    filterLife: "2,500 hours (about 3–4 months)",
    filtration: "Pre-filter, HEPA, active carbon composite",
    sound: "Sleep 21.7; speeds 21.2 / 32.3 / 42.7 / 60.6 dBA",
    wheels: "No",
    warranty: "Limited lifetime; current terms and registration still apply",
    filter: "MA-50 V3.0 filter only; verify revision before advising",
    reset: "V3.0 instructions must not be used for older MA-50 revisions",
    image: `${ASSET_BASE}products/ma-50.png`,
    source: "https://medifyair.com/products/ma-50-air-purifier",
    sourceLabel: "Official MA-50 V3.0 product page",
    summary: "High-capacity active model. Revision identification is mandatory before filter or reset guidance.",
    flags: ["Older MA-50 UV and earlier revisions are support-only."]
  },
  {
    id: "ma-112",
    model: "MA-112",
    revision: "White · standard non-UV",
    status: "Active",
    finderEligible: true,
    coverage: 2228,
    cadr: 594,
    cadrMetric: 1009,
    dimensions: "28 H × 16 W × 16 D in",
    weight: "33.5 lb",
    wattage: "95 W",
    speeds: "4",
    controls: "Timer, four speeds, sleep, indicator, touch controls, child lock",
    filterLife: "3,000 hours (about 4–5 months)",
    filtration: "Pre-filter, HEPA, active carbon composite",
    sound: "Needs Confirmation — the current source table appears mislabeled",
    wheels: "Yes",
    warranty: "Limited lifetime; current terms and registration still apply",
    filter: "Use the exact white standard MA-112 replacement filter",
    reset: "Use the exact current MA-112 manual",
    image: `${ASSET_BASE}products/ma-112.png`,
    source: "https://medifyair.com/products/ma-112",
    sourceLabel: "Official MA-112 product page",
    summary: "Largest resolved single-unit threshold in the automatic finder.",
    flags: ["Sound-level labels need confirmation; sizing coverage remains 2,228 sq ft."]
  },
  {
    id: "ma-112-pro",
    model: "MA-112 PRO",
    revision: "White · commercial",
    status: "Needs confirmation",
    finderEligible: false,
    coverage: null,
    coverageDisplay: "2,228 / 2,947 / 2,974 sq ft conflict",
    cadr: 793,
    cadrMetric: 1347,
    dimensions: "28 H × 13 W × 13 D in",
    weight: "29.5 lb",
    wattage: "95 W",
    speeds: "4",
    controls: "Timer, four speeds, sleep, indicator, touch controls, child lock; no UV or ionizer",
    filterLife: "3,000 hours (about 4–5 months)",
    filtration: "Pre-filter, HEPA, active carbon composite",
    sound: "24.6 / 41.7 / 52.3 / 58.1 dBA",
    wheels: "Yes",
    warranty: "Limited lifetime; current terms and registration still apply",
    filter: "Verify the exact MA-112 PRO replacement filter",
    reset: "Use only the MA-112 PRO manual",
    image: `${ASSET_BASE}products/ma-112-pro.png`,
    source: "https://medifyair.com/products/ma-112-pro-air-purifier-white",
    sourceLabel: "Official MA-112 PRO product page",
    summary: "Active commercial profile, excluded from automatic sizing until conflicting official coverage values are resolved.",
    flags: ["Critical coverage conflict. Do not use this model for automatic sizing."]
  }
];

export const supportOnlyProducts = [
  ["MA-125", "Discontinued", "New-sale recommendations are disabled; preserve support history only."],
  ["MA-14", "Discontinued", "Excluded from new-purchase recommendations despite a conflicting live page."],
  ["MA-10", "Discontinued", "Legacy support only."],
  ["MA-18", "Discontinued", "Legacy support only."],
  ["MA-15", "Filter support only", "Unit is decommissioned; compatible-filter support remains."],
  ["MA-40 UV / Black", "Discontinued variant", "Keep separate from the white standard MA-40."],
  ["MA-25 Black / Silver", "Discontinued colors", "Current finder uses the white revision only."],
  ["MA-112 Black / UV", "Discontinued variants", "Current finder uses the white standard revision only."],
  ["MA-50 older UV", "Legacy revisions", "Never inherit V3.0 filter or reset instructions."],
  ["MA-35 table stand", "Discontinued accessory", "Do not present as part of the current unit offering."]
];

const workflowRows = [
  ["WF-001", "WISMO — unfulfilled", "Orders & shipping", "Ready with live lookup", "Check processing state against the current 1–3 business-day window."],
  ["WF-002", "WISMO — in transit", "Orders & shipping", "Ready with live lookup", "Separate label created, moving, delayed, exception, and return-to-sender."],
  ["WF-003", "Delivered not received", "Orders & shipping", "Blocked", "Carrier waiting threshold is unresolved; collect facts and route safely."],
  ["WF-004", "Missing item / split shipment", "Orders & shipping", "Ready with live lookup", "Check every tracking number before treating an item as missing."],
  ["WF-005", "Damaged shipment", "Orders & shipping", "Guided", "Collect complete damage evidence and keep remedy pending until approval."],
  ["WF-006", "UPS claim", "Orders & shipping", "Needs confirmation", "File or hand off an eligible claim without promising the result."],
  ["WF-007", "Order cancellation", "Orders & shipping", "Needs live system", "Confirm the actual system outcome before telling the customer it was canceled."],
  ["WF-008", "Address change", "Orders & shipping", "Needs live system", "Check fulfillment state before attempting a permitted address change."],
  ["WF-009", "Change-of-mind return", "Returns & refunds", "Guided", "Verify purchase channel, current window, condition, packaging, and return states."],
  ["WF-010", "Wrong item", "Returns & refunds", "Needs confirmation", "Verify ordered and received items with label and item photos."],
  ["WF-011", "Refund request", "Returns & refunds", "Guided", "Separate request, authorization, processor completion, and bank posting."],
  ["WF-012", "Warranty intake", "Warranty & troubleshooting", "Guided with blockers", "Build a complete eligibility and evidence packet without promising approval."],
  ["WF-013", "Troubleshooting — general", "Warranty & troubleshooting", "Ready with model guardrail", "Identify the exact model and revision before model-specific steps."],
  ["WF-014", "No-power branch", "Warranty & troubleshooting", "Ready with model guardrail", "Run only safe, model-appropriate power checks."],
  ["WF-015", "Filter indicator / reset", "Warranty & troubleshooting", "Blocked", "Reset steps vary by model and revision; exact identification is required."],
  ["WF-016", "MA-40 vs MA-40 UV", "Warranty & troubleshooting", "Ready with model guardrail", "Read the full model sticker and use only the matching instructions."],
  ["WF-017", "MA-50 fit / beep", "Warranty & troubleshooting", "Needs revision map", "Do not use V3.0 steps on an older revision."],
  ["WF-018", "Manual request", "Products", "Ready", "Send only the exact official public manual for the model and revision."],
  ["WF-019", "Room-size finder", "Products", "Ready", "Use current active, resolved coverage thresholds and show all assumptions."],
  ["WF-020", "Advanced sizing", "Products", "Planning estimate", "Adjust for ceiling height and route unusual spaces to assisted sizing."],
  ["WF-021", "Product detail profile", "Products", "Ready", "Show verified fields, source dates, and unresolved values visibly."],
  ["WF-022", "Filter Club — cancel", "Filter Club", "Needs live system", "Distinguish the subscription from any order already created."],
  ["WF-023", "Filter Club — change", "Filter Club", "Needs live system", "Restate the resulting next charge and cadence after confirmation."],
  ["WF-024", "Filter Club — payment", "Filter Club", "Ready with security guardrail", "Use secure self-service; never collect full card details."],
  ["WF-025", "Amazon / reseller routing", "Marketplace", "Needs confirmation", "Identify the transaction owner before offering a return or refund path."],
  ["WF-026", "Duplicate ticket", "Internal operations", "Needs current tool policy", "Preserve one owner and never lose unresolved customer work."],
  ["WF-027", "Snooze / follow-up", "Internal operations", "Needs confirmation", "Record the pending item, owner, and next checkpoint."],
  ["WF-028", "L2 handoff", "Internal operations", "Ready", "Send facts, evidence, actions, requested decision, and urgency."],
  ["WF-029", "Voice call note", "Voice", "Ready", "Generate the exact approved headings and leave JA empty."],
  ["WF-030", "Security incident", "Security", "Immediate action", "Do not reproduce a secret; restrict, report, remove, and rotate."]
];

export const workflows = workflowRows.map(([id, title, category, status, summary]) => ({
  id,
  title,
  category,
  status,
  summary,
  fullyGuided: ["WF-005", "WF-009", "WF-011", "WF-012", "WF-013", "WF-014", "WF-018", "WF-019", "WF-021", "WF-024", "WF-028", "WF-029", "WF-030"].includes(id)
}));

const commonSources = {
  warranty: "Internal troubleshooting + official warranty page (SRC-106, SRC-201)",
  shipping: "Internal shipping/claim procedures + public shipping policy (SRC-102, SRC-107, SRC-203)",
  return: "Internal return/refund procedures + public shipping policy (SRC-103, SRC-104, SRC-203)"
};

export const guidedFlows = {
  "WF-012": {
    title: "Warranty intake & replacement assessment",
    purpose: "Identify the exact unit, complete safe troubleshooting, gather evidence, and route a decision-ready packet without implying approval.",
    channel: "All",
    status: "Needs confirmation",
    source: commonSources.warranty,
    steps: [
      {
        id: "unit",
        title: "Identify the exact unit",
        question: "Can you confirm the exact model and revision from the unit label?",
        choices: ["Exact model and revision confirmed", "Model known, revision unclear", "Customer cannot access the label"],
        need: "Model, revision or variant, serial if policy permits, and the reported symptom.",
        why: "Controls, filters, reset steps, and feature variants differ across models and revisions.",
        ask: "Please read the complete model information shown on the unit label. A clear photo is best if available.",
        evidence: "Clear model-label photo when the revision cannot be confirmed verbally.",
        check: "Match the model and revision to the exact current or legacy product profile.",
        action: "Record the exact label wording before giving model-specific steps.",
        notPromise: "Do not assume UV, ionizer, Auto mode, filter, or reset behavior from the model family alone.",
        result: "Exact unit identity is confirmed, or the case is visibly blocked pending a label photo.",
        source: "SRC-106 · Technical Troubleshooting",
        verified: VERIFIED_ON
      },
      {
        id: "purchase",
        title: "Verify purchase and registration",
        question: "Which purchase channel can be verified?",
        choices: ["Medify direct", "Amazon", "Authorized reseller / other", "Purchase source not yet verified"],
        need: "Purchase source, purchase date, order or invoice, and current registration evidence.",
        why: "The transaction owner and applicable warranty path depend on the sales channel and current agreement.",
        ask: "Where and when was the unit purchased, and do you have the receipt or order confirmation?",
        evidence: "Proof of purchase and registration record when required by the current agreement.",
        check: "Confirm the seller, purchase date, and exact agreement that applies to the model/revision.",
        action: "Attach or reference non-sensitive proof; never copy more personal data than the case needs.",
        notPromise: "Do not state that the purchase is eligible until current terms and required evidence are verified.",
        result: "Purchase ownership is clear and the case can move to troubleshooting or a channel handoff.",
        source: "SRC-108, SRC-201 · Warranty handling and registration",
        verified: VERIFIED_ON
      },
      {
        id: "diagnosis",
        title: "Complete model-safe diagnosis",
        question: "What is the current troubleshooting state?",
        choices: ["Issue resolved during troubleshooting", "Issue persists and evidence is complete", "Issue persists but evidence is missing", "Potential safety issue"],
        need: "Symptom, exact steps attempted, results, and a short photo/video when unresolved.",
        why: "A replacement decision needs a documented defect, not only a symptom description.",
        ask: "What happens when you try the exact step, and can you send a clear 5–8 second video if the issue remains?",
        evidence: "Troubleshooting chronology plus relevant photo/video; never request unsafe testing.",
        check: "Use only the exact model/revision guide and stop for heat, smoke, burning odor, exposed wiring, or unsafe damage.",
        action: "Record each completed step and result. For safety risk, stop use and escalate according to current safety policy.",
        notPromise: "Do not promise a replacement merely because evidence was requested or uploaded.",
        result: "Resolved, decision-ready evidence packet, awaiting evidence, or safety escalation.",
        source: "SRC-106 · Technical Troubleshooting",
        verified: VERIFIED_ON
      },
      {
        id: "eligibility",
        title: "Apply the policy gate",
        question: "Is a current, model-specific eligibility decision available?",
        choices: ["Eligible decision documented", "Not eligible decision documented", "Awaiting L2 / policy owner", "Current rule conflicts with source material"],
        need: "Exact agreement, registration state, evidence packet, and dated approval or denial.",
        why: "Registration timing, genuine-filter language, and defective-unit return rules have unresolved source conflicts.",
        ask: "I have the information needed for review. I’ll explain the confirmed next step once the decision is recorded.",
        evidence: "The approval/denial record or a complete escalation packet.",
        check: "Never resolve the 30-versus-90-day registration or defective-unit return conflict from memory.",
        action: "If no dated rule applies, mark Needs Confirmation and send the complete packet to the accountable owner.",
        notPromise: "Do not say approved, replaced, return, discard, keep, or re-register until the current case decision confirms it.",
        result: "A documented decision or a clearly owned pending approval.",
        source: "CON-001, CON-002, CON-003 · Open policy conflicts",
        verified: VERIFIED_ON
      },
      {
        id: "outcome",
        title: "Confirm the actual outcome",
        question: "Which outcome has actually been completed?",
        choices: ["Troubleshooting resolved the issue", "Replacement approved — creation still pending", "Replacement created and reference confirmed", "Not eligible — approved explanation ready", "Still awaiting approval / customer evidence"],
        need: "The last completed action, the exact pending item, owner, and next checkpoint.",
        why: "Approval and creation are different states; pending work cannot be recorded as completed.",
        ask: "Here is the action that is complete and the next step that is still pending.",
        evidence: "Live system confirmation for any replacement or final decision.",
        check: "Separate replacement approved from replacement created; record any required return only if the case decision says so.",
        action: "Generate channel wording and internal notes from confirmed answers only.",
        notPromise: "Do not give an unverified ship date or imply the customer’s case is closed while an action is pending.",
        result: "Accurate customer message, internal note, owner, and next step.",
        source: commonSources.warranty,
        verified: VERIFIED_ON
      }
    ]
  },
  "WF-005": {
    title: "Lost, missing, or damaged shipment",
    purpose: "Classify the shipping issue, collect the correct evidence, and preserve carrier or approval states without promising a remedy.",
    channel: "All",
    status: "Needs confirmation",
    source: commonSources.shipping,
    steps: [
      {
        id: "shipment-state",
        title: "Classify the shipment state",
        question: "What does the latest verified shipment record show?",
        choices: ["In transit with current movement", "Stuck / delayed / carrier exception", "Marked delivered but not received", "Arrived damaged", "Missing item / partial shipment"],
        need: "Order source, order number, tracking, destination check, latest scan, and affected items.",
        why: "Each state has different evidence and timing requirements, and shipping claims are not warranty cases.",
        ask: "Please confirm the tracking number, latest carrier message, and exactly what was or was not received.",
        evidence: "Carrier status and order/package details.",
        check: "Review every package and tracking number before classifying a short shipment.",
        action: "Select the matching branch and record the latest verified event.",
        notPromise: "Do not promise an arrival date, replacement, or refund from an unverified carrier state.",
        result: "One precise shipment state with the correct next branch.",
        source: "SRC-102, SRC-109, SRC-203",
        verified: VERIFIED_ON
      },
      {
        id: "evidence",
        title: "Collect branch evidence",
        question: "Is the evidence packet complete for this shipment state?",
        choices: ["Complete", "Partially complete", "Awaiting customer", "Evidence unavailable — escalation needed"],
        need: "For damage: packaging, shipping label, box, and product photos. For missing delivery: address match, proof of delivery, and customer location checks.",
        why: "Carrier and operations reviewers cannot make a safe decision from an incomplete or mismatched packet.",
        ask: "Please send clear photos of the shipping label, outside of the box, packaging, and affected product, or confirm the delivery-location checks requested.",
        evidence: "Only the evidence relevant to the selected shipping branch.",
        check: "Confirm the address safely without repeating unnecessary personal data in internal output.",
        action: "Mark each evidence item received, missing, or not applicable.",
        notPromise: "Do not say a claim is filed or approved while evidence is still being collected.",
        result: "Complete packet or an explicit Awaiting customer state.",
        source: "SRC-102, SRC-107",
        verified: VERIFIED_ON
      },
      {
        id: "claim-gate",
        title: "Check the claim gate",
        question: "What is the current claim or approval state?",
        choices: ["Not yet eligible / waiting", "Eligible and ready to submit", "Claim submitted — decision pending", "Claim approved", "Claim declined / exception"],
        need: "Current carrier rule, filing window, claim owner, and any approved exception.",
        why: "Source material conflicts on a 3-business-day versus 5-day delivered-not-received threshold.",
        ask: "I’ll keep you updated once the required carrier or operations review reaches its next confirmed state.",
        evidence: "Claim record or dated owner decision.",
        check: "For delivered-not-received cases, do not choose a waiting threshold from memory; route the unresolved rule.",
        action: "Record the exact state: eligible, submitted, approved, declined, or awaiting owner confirmation.",
        notPromise: "Do not promise a replacement or refund before the authorized result.",
        result: "Accurate pending or terminal claim state.",
        source: "CON-004, CON-005 · Open shipping conflicts",
        verified: VERIFIED_ON
      },
      {
        id: "remedy",
        title: "Confirm the authorized remedy",
        question: "Which remedy state is verified?",
        choices: ["No remedy authorized yet", "Replacement approved — not created", "Replacement created", "Refund authorized — processing", "Other approved resolution"],
        need: "Decision owner, completed action, pending action, and next customer update.",
        why: "Claim submission, claim approval, replacement approval, replacement creation, and refund completion are distinct.",
        ask: "I’ll state what has been completed and what is still pending, with the next update point.",
        evidence: "Live system confirmation or a dated authorized decision.",
        check: "Make sure the remedy matches the exact affected item and shipment.",
        action: "Generate customer wording and internal notes using only the confirmed state.",
        notPromise: "Do not turn an approval into a shipment promise or a refund request into a completed refund.",
        result: "A factual outcome message and an owned pending next step.",
        source: commonSources.shipping,
        verified: VERIFIED_ON
      }
    ]
  },
  "WF-009": {
    title: "Return & refund",
    purpose: "Verify the channel and current eligibility, collect required condition evidence, and track every return and refund state separately.",
    channel: "All",
    status: "Needs confirmation",
    source: commonSources.return,
    steps: [
      {
        id: "return-intake",
        title: "Verify the purchase and request",
        question: "Which purchase channel owns the transaction?",
        choices: ["Medify direct", "Amazon", "Authorized reseller / other", "Purchase source unclear"],
        need: "Purchase source, order number, receipt date, affected item, and return reason.",
        why: "Medify cannot automatically process a return or refund owned by another seller.",
        ask: "Where was the item purchased, when was it received, and what is the reason for the return?",
        evidence: "Proof of purchase or order record.",
        check: "Confirm the transaction owner and current public return window before stating eligibility.",
        action: "Classify the channel and record the requested resolution.",
        notPromise: "Do not promise a label or refund until the correct owner and eligibility are confirmed.",
        result: "Correct channel path and complete intake.",
        source: "SRC-103, SRC-203",
        verified: VERIFIED_ON
      },
      {
        id: "condition",
        title: "Confirm item condition",
        question: "What is the verified item and packaging state?",
        choices: ["Unused / complete packaging", "Used but complete", "Damaged or defective", "Filter seal or packaging state unclear"],
        need: "Product, packaging, filter/seal, shipping-label, and condition details required by the current policy.",
        why: "Eligibility and handling may depend on condition, packaging, filter seals, and whether the issue is a return, damage, or warranty case.",
        ask: "Please provide clear photos of the item, included packaging, filter/seal state, and shipping label.",
        evidence: "Current required photo set.",
        check: "Do not merge carrier damage or a proven product defect into a change-of-mind return.",
        action: "Mark every required evidence item received, missing, or not applicable.",
        notPromise: "Do not tell the customer to ship anything until eligibility and routing are confirmed.",
        result: "Decision-ready condition packet or Awaiting customer.",
        source: "SRC-103, SRC-203",
        verified: VERIFIED_ON
      },
      {
        id: "eligibility",
        title: "Confirm eligibility and label state",
        question: "What has actually been confirmed?",
        choices: ["Eligible — label not created", "Label created", "Outside standard window — approval pending", "Not eligible — approved explanation available", "Needs Confirmation"],
        need: "Current window, any exception approval, warehouse route, and label record.",
        why: "The public 30-day rule, legacy holiday windows, fees, and routing have mixed-era source material.",
        ask: "I’ll provide the confirmed next step after the current eligibility review is complete.",
        evidence: "Current policy source or dated exception approval.",
        check: "Do not use legacy holiday or warehouse routing rules without current confirmation.",
        action: "Record eligibility, label created/not created, and the next owner.",
        notPromise: "A return request is not a label; a label is not warehouse receipt; receipt is not refund completion.",
        result: "Accurate return state and routing.",
        source: "CON-019, CON-020 · Open return-policy conflicts",
        verified: VERIFIED_ON
      },
      {
        id: "return-state",
        title: "Track the return",
        question: "Which return state is verified?",
        choices: ["Label created — no carrier movement", "In carrier movement", "Warehouse received", "Inspection / authorization pending", "Return exception"],
        need: "Return tracking, last scan, warehouse receipt, and inspection/authorization state.",
        why: "The refund trigger must be tied to the current verified return state.",
        ask: "Here is the current return status and the next step that must occur before the refund can move forward.",
        evidence: "Carrier and warehouse/system record.",
        check: "Confirm the event instead of inferring it from elapsed time.",
        action: "Record the exact verified state and next checkpoint.",
        notPromise: "Do not promise a refund date from a label or carrier scan alone.",
        result: "One verified return state with an owner and next checkpoint.",
        source: "SRC-103, SRC-104",
        verified: VERIFIED_ON
      },
      {
        id: "refund-state",
        title: "Confirm refund status",
        question: "Which refund state is verified?",
        choices: ["Not yet authorized", "Refund requested", "Refund authorized / processor pending", "Refund completed by processor", "Refund failed / requires escalation"],
        need: "Approved amount, items/tax, processor result, and next customer checkpoint.",
        why: "An internal refund action and the customer’s bank posting are separate events.",
        ask: "I’ll confirm the processor state and avoid promising a bank-posting date that is outside our control.",
        evidence: "Live processor or authorized finance record.",
        check: "Confirm amount and transaction owner before communicating completion.",
        action: "Generate channel copy and internal notes from the verified state.",
        notPromise: "Do not call a requested or authorized refund completed until the processor confirms it.",
        result: "Accurate refund status and pending next step.",
        source: commonSources.return,
        verified: VERIFIED_ON
      }
    ]
  }
};

export const sources = [
  ["SRC-101", "Process & Product Updates 2026", "Internal procedure updates", "Verified", "Updates through Jul 9, 2026", "https://sites.google.com/wagmisolutions.io/medify-air-internal-kb/process-product-updates-2026"],
  ["SRC-106", "Technical Troubleshooting", "Internal procedure", "Verified with safeguards", VERIFIED_ON, "https://sites.google.com/wagmisolutions.io/medify-air-internal-kb/csr/technical-troubleshooting"],
  ["SRC-200", "Product Manuals", "Official public", "Verified", VERIFIED_ON, "https://medifyair.com/pages/product-manuals"],
  ["SRC-201", "Warranty Registration", "Official public", "Verified", VERIFIED_ON, "https://medifyair.com/pages/warranty"],
  ["SRC-202", "Filter Club", "Official public", "Verified", VERIFIED_ON, "https://medifyair.com/pages/filterclub"],
  ["SRC-203", "Shipping Policy", "Official public", "Verified", VERIFIED_ON, "https://medifyair.com/pages/shipping-policy"],
  ["SRC-211", "MA-22 product page", "Official model", "Verified", VERIFIED_ON, "https://medifyair.com/products/ma-22-air-purifier"],
  ["SRC-212", "MA-25 product page", "Official model", "Approved resolution", VERIFIED_ON, "https://medifyair.com/products/medify-ma-25-air-purifier"],
  ["SRC-213", "MA-35 product page", "Official model", "Approved resolution", VERIFIED_ON, "https://medifyair.com/products/ma-wm35"],
  ["SRC-214", "MA-40 product page", "Official model", "Verified", VERIFIED_ON, "https://medifyair.com/products/medify-ma-40"],
  ["SRC-215", "MA-50 V3.0 product page", "Official model", "Verified", VERIFIED_ON, "https://medifyair.com/products/ma-50-air-purifier"],
  ["SRC-216", "MA-112 product page", "Official model", "Partial — sound field open", VERIFIED_ON, "https://medifyair.com/products/ma-112"]
];

export const conflicts = [
  ["Critical", "Security", "A restricted warranty source exposed a credential.", "Secret values were excluded. Rotate/remove the credential and sanitize source history."],
  ["High", "Warranty", "Defective-unit return handling conflicts across sources.", "Approve one dated rule, evidence standard, and exception owner."],
  ["High", "Warranty", "Registration timing appears as 30 days and 90 days.", "Confirm the current window and grandfathering."],
  ["High", "Shipping", "Delivered-not-received waiting period appears as 3 and 5 business days.", "Choose a rule or define scenario-specific thresholds."],
  ["High", "Shipping", "Immediate replacement language conflicts with carrier no-promise guidance.", "Define who may approve an exception and at what state."],
  ["High", "Product", "MA-112 PRO coverage appears as 2,228, 2,947, and 2,974 sq ft.", "Keep excluded from automatic sizing until approved lab/current-revision value is supplied."],
  ["High", "Product", "MA-50 revisions have different filter and reset behavior.", "Use an exact revision matrix before model-specific instructions."],
  ["High", "Privacy", "Legacy files contain private URLs, local paths, examples, and named routing.", "Keep migration sanitizer and release-time secret/PII scan mandatory."]
];

export const scriptLibrary = {
  Email: {
    title: "Evidence request — unresolved product issue",
    text: "Hi [Customer Name],\n\nThank you for working through the troubleshooting steps with us. To continue the review, please reply with the exact model/revision shown on the unit label, proof of purchase, and a clear 5–8 second video showing the issue.\n\nOnce the required information is complete, we’ll route the case for the appropriate review. This message does not mean a warranty claim or replacement has been approved.\n\nBest,\nMedify Air Support"
  },
  Chat: {
    title: "Shipping claim — pending review",
    text: "Thanks for confirming those details. I’ve documented the verified shipment state and the evidence received. The carrier/operations decision is still pending, so I don’t want to promise a replacement or refund before that result is confirmed. The next step is [Pending Step], owned by [Owner]."
  },
  Voice: {
    title: "Return status — live call line",
    text: "I can confirm that [Completed State] is complete. The refund is not complete yet; the current pending step is [Pending Step]. I’ll document the owner and the next checkpoint so you know exactly what happens next."
  }
};

export const noteHeadings = [
  "Spoke With",
  "Name on the Account",
  "Order Num",
  "Email Address",
  "Contact #",
  "Reason for Calling",
  "ACTION TAKEN",
  "Offered FC/Cross Sell",
  "AC Call ID",
  "JA"
];

export const synonyms = {
  "wismo": "where is my order tracking shipping",
  "lost": "missing delivered not received carrier ups",
  "broken": "warranty defect troubleshooting replacement",
  "refund": "return money reimbursement processor",
  "filter light": "indicator reset filter change",
  "purifer": "purifier air cleaner model",
  "subscrption": "subscription filter club recharge",
  "ma40": "ma-40 standard uv",
  "ma50": "ma-50 v3 revision"
};
